[package]
name = "chatgpt-translator"
version = "0.4.0"
edition = "2021"
description = "An OpenAI-powered Markdown document tranlator. Translate your clipboard text into any language."

[[bin]]
name = "ct"
path = "src/main.rs"

[lib]
name = "chatgpt_translator"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.86"
arboard = "3.4.0"
async-openai = "0.23.3"
clap = { version = "4.5.8", features = ["derive", "env"] }
regex = "1.10.5"
tokio = { version = "1.38.0", features = ["full"] }
xdg = "2.5.2"
